### Builds sql/procedures/run_pipeline.sql by reading existing SQL files
### and applying transformations. See top of run_pipeline.sql for details.

$ErrorActionPreference = 'Stop'
$repo = "C:\Users\ArlindGreba\polaris"
$out  = "$repo\sql\procedures\run_pipeline.sql"

$stgTables = @(
  'v6_stg_lcoe_model_controls','v6_stg_project_timeline','v6_stg_project_capacity',
  'v6_stg_generation_seasonality','v6_stg_degradation','v6_stg_tax_attributes',
  'v6_stg_financing_fees','v6_stg_contingency','v6_stg_capex_unit_cost',
  'v6_stg_opex_rates','v6_stg_insurance','v6_stg_property_tax',
  'v6_stg_franchise_tax','v6_stg_land_lease','v6_stg_other_expenses',
  'v6_stg_gas_opex','v6_stg_dtc_opex','v6_stg_operating_lcs'
)
$silverTables = @(
  'v6_silver_project_inputs','v6_silver_capex_components','v6_silver_opex_all_rates',
  'v6_silver_generation_profile','v6_silver_itc_inputs','v6_silver_operating_lcs'
)
$fctTables = @(
  'project_timeline_monthly','generation_monthly','project_capex_monthly',
  'project_opex_monthly','tax_credit_monthly','depreciation_monthly',
  'revenue_monthly','lcoe_component_annual','lcoe_facility_summary'
)
$fctFileMap = @{
  'project_timeline_monthly'='v6_fct_project_timeline_monthly.sql'
  'generation_monthly'='v6_fct_generation_monthly.sql'
  'project_capex_monthly'='v6_fct_capex_monthly.sql'
  'project_opex_monthly'='v6_fct_opex_monthly.sql'
  'tax_credit_monthly'='v6_fct_tax_credit_monthly.sql'
  'depreciation_monthly'='v6_fct_depreciation_monthly.sql'
  'revenue_monthly'='v6_fct_revenue_monthly.sql'
  'lcoe_component_annual'='v6_fct_lcoe_component_annual.sql'
  'lcoe_facility_summary'='v6_fct_lcoe_facility_summary.sql'
}

# Multi-line tolerant regex: a (SELECT run_id FROM `X` ORDER BY pushed_at DESC LIMIT 1) subquery
# We preserve the parens because the same shape is also used as a CTE body:
#   xxx AS (SELECT run_id FROM ... ORDER BY pushed_at DESC LIMIT 1)
# Replacing the parens too would yield `xxx AS current_run_id` (invalid).
# Replacing the body to `SELECT current_run_id AS run_id` works in every context.
$limit1Pattern     = '\(\s*SELECT\s+run_id\s+FROM\s+`[^`]+`\s+ORDER\s+BY\s+pushed_at\s+DESC\s+LIMIT\s+1\s*\)'
$limit1Replacement = '(SELECT current_run_id AS run_id)'

$sb = [System.Text.StringBuilder]::new()

# ============================================================
# Header
# ============================================================
[void]$sb.AppendLine(@'
-- =============================================================================
-- Polaris V6 - run_pipeline procedure
-- =============================================================================
-- Processes all run_ids in polaris_raw.v6_raw_inputs_tab that have not yet
-- been loaded into fct_finance.project_timeline_monthly. For each unprocessed
-- run_id (in pushed_at order) the procedure:
--   1. DELETEs any partial state for that run_id across all 33 tables
--   2. INSERTs into 18 stg_finance.v6_stg_* tables
--   3. INSERTs into 6 mart_finance.v6_silver_* tables
--   4. INSERTs into 9 fct_finance.* tables in dependency order
--
-- Idempotency: skip-check on fct.project_timeline_monthly guards re-processing;
-- DELETE-then-INSERT inside the loop tolerates partial-failure restarts.
--
-- Logging: per-run / per-stage rows accumulated in a TEMP TABLE returned at end.
--
-- Generated by sql/procedures/_build_run_pipeline.ps1
-- =============================================================================

CREATE OR REPLACE PROCEDURE `sandbox-lakehouse.polaris_raw.run_pipeline`()
BEGIN
  DECLARE current_run_id   STRING;
  DECLARE processed_count  INT64 DEFAULT 0;
  DECLARE skipped_count    INT64 DEFAULT 0;

  CREATE TEMP TABLE _log (
    ts          TIMESTAMP,
    event       STRING,
    run_id      STRING,
    detail      STRING
  );

  INSERT INTO _log VALUES (
    CURRENT_TIMESTAMP(), 'PIPELINE_START', NULL,
    FORMAT('Distinct run_ids in raw: %d',
      (SELECT COUNT(DISTINCT run_id) FROM `sandbox-lakehouse.polaris_raw.v6_raw_inputs_tab`))
  );

  FOR rec IN (
    SELECT run_id
    FROM (
      SELECT run_id, MIN(pushed_at) AS first_push
      FROM `sandbox-lakehouse.polaris_raw.v6_raw_inputs_tab`
      GROUP BY run_id
    )
    ORDER BY first_push
  ) DO
    SET current_run_id = rec.run_id;

    IF EXISTS (
      SELECT 1 FROM `sandbox-lakehouse.fct_finance.project_timeline_monthly`
      WHERE run_id = current_run_id
    ) THEN
      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'SKIP', current_run_id,
        'Already present in fct.project_timeline_monthly');
      SET skipped_count = skipped_count + 1;
    ELSE
      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'RUN_START', current_run_id, NULL);

'@)

# ============================================================
# DELETE block
# ============================================================
[void]$sb.AppendLine("      -- ---- DELETE: purge partial state for current_run_id ----")
foreach ($t in $stgTables) {
  [void]$sb.AppendLine("      DELETE FROM `sandbox-lakehouse.stg_finance.$t` WHERE run_id = current_run_id;")
}
foreach ($t in $silverTables) {
  [void]$sb.AppendLine("      DELETE FROM `sandbox-lakehouse.mart_finance.$t` WHERE run_id = current_run_id;")
}
foreach ($t in $fctTables) {
  [void]$sb.AppendLine("      DELETE FROM `sandbox-lakehouse.fct_finance.$t` WHERE run_id = current_run_id;")
}
# Purge any prior audit rows for this run_id so the post-fct insert is idempotent.
[void]$sb.AppendLine("      DELETE FROM `sandbox-lakehouse.polaris_raw.run_audit` WHERE run_id = current_run_id;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'DELETE_DONE', current_run_id, NULL);")
[void]$sb.AppendLine("")

# ============================================================
# STAGING
# ============================================================
[void]$sb.AppendLine("      -- ---- STAGING (18 tables) ----")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'STG_START', current_run_id, NULL);")
[void]$sb.AppendLine("")

$staging = Get-Content "$repo\sql\staging\v6_master_staging.sql" -Raw -Encoding UTF8
$staging = $staging -replace '^Master V6 Staging query\r?\n', ''
# CREATE OR REPLACE TABLE -> INSERT INTO
$staging = [regex]::Replace($staging,
  'CREATE OR REPLACE TABLE `(sandbox-lakehouse\.stg_finance\.[^`]+)` AS',
  'INSERT INTO `$1`')
# Multi-line tolerant: any (SELECT run_id FROM `X` ORDER BY pushed_at DESC LIMIT 1) -> (SELECT current_run_id AS run_id)
$staging = [regex]::Replace($staging, $limit1Pattern, $limit1Replacement)
# Indent
$stagingIndented = ($staging -split "`n" | ForEach-Object { if ($_ -match '\S') { "      $_" } else { "" } }) -join "`n"
[void]$sb.AppendLine($stagingIndented)
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'STG_DONE', current_run_id, NULL);")
[void]$sb.AppendLine("")

# ============================================================
# SILVER
# ============================================================
[void]$sb.AppendLine("      -- ---- SILVER (6 tables) ----")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'SILVER_START', current_run_id, NULL);")
[void]$sb.AppendLine("")

$silver = Get-Content "$repo\sql\silver\v6_silver_consolidated.sql" -Raw -Encoding UTF8
$silver = $silver -replace '^v6 silver consolidated query\r?\n', ''
# CREATE OR REPLACE TABLE -> INSERT INTO
$silver = [regex]::Replace($silver,
  'CREATE OR REPLACE TABLE `(sandbox-lakehouse\.mart_finance\.v6_silver_[^`]+)` AS',
  'INSERT INTO `$1`')
# FROM `stg_finance.v6_stg_X` -> FROM (SELECT * FROM `...` WHERE run_id = current_run_id)
# Use FROM prefix so we never touch INSERT INTO targets
$silver = [regex]::Replace($silver,
  'FROM\s+`(sandbox-lakehouse\.stg_finance\.v6_stg_[^`]+)`',
  'FROM (SELECT * FROM `$1` WHERE run_id = current_run_id)')
# FROM `mart_finance.v6_silver_capex_components` (used by v6_silver_itc_inputs)
$silver = [regex]::Replace($silver,
  'FROM\s+`(sandbox-lakehouse\.mart_finance\.v6_silver_capex_components)`',
  'FROM (SELECT * FROM `$1` WHERE run_id = current_run_id)')
# Multi-line LIMIT 1 cleanup (defensive — silver shouldn't have any but cover the case)
$silver = [regex]::Replace($silver, $limit1Pattern, $limit1Replacement)
$silverIndented = ($silver -split "`n" | ForEach-Object { if ($_ -match '\S') { "      $_" } else { "" } }) -join "`n"
[void]$sb.AppendLine($silverIndented)
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'SILVER_DONE', current_run_id, NULL);")
[void]$sb.AppendLine("")

# ============================================================
# FCT
# ============================================================
[void]$sb.AppendLine("      -- ---- FCT (9 tables in dependency order) ----")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'FCT_START', current_run_id, NULL);")
[void]$sb.AppendLine("")

$fctList = ($fctTables | ForEach-Object { [regex]::Escape($_) }) -join '|'
foreach ($t in $fctTables) {
  $f = $fctFileMap[$t]
  $content = Get-Content "$repo\sql\fct\$f" -Raw -Encoding UTF8
  $idx = $content.IndexOf("INSERT INTO ``sandbox-lakehouse.fct_finance.")
  if ($idx -lt 0) { throw "INSERT INTO not found in $f" }
  $insertPart = $content.Substring($idx)
  # Multi-line LIMIT 1 subqueries -> (SELECT current_run_id AS run_id)
  $insertPart = [regex]::Replace($insertPart, $limit1Pattern, $limit1Replacement)
  # canonical CTE: replace `FROM stg_project_timeline\nORDER BY pushed_at DESC LIMIT 1`
  # with a WHERE filter + LIMIT 1. Must keep LIMIT 1 — downstream CTEs reference
  # canonical as a scalar (`WHERE run_id = (SELECT run_id FROM canonical)`) so it
  # must return exactly one row, not one per technology.
  $insertPart = [regex]::Replace($insertPart,
    'FROM\s+`sandbox-lakehouse\.stg_finance\.v6_stg_project_timeline`\s+ORDER\s+BY\s+pushed_at\s+DESC\s+LIMIT\s+1',
    "FROM ``sandbox-lakehouse.stg_finance.v6_stg_project_timeline```n  WHERE run_id = current_run_id`n  LIMIT 1")
  # Wrap fct->fct cross-references in a run_id filter subquery (FROM prefix only)
  $insertPart = [regex]::Replace($insertPart,
    "FROM\s+``(sandbox-lakehouse\.fct_finance\.(?:$fctList))``",
    'FROM (SELECT * FROM `$1` WHERE run_id = current_run_id)')
  # Wrap silver references in fct (FROM only) for safety
  $insertPart = [regex]::Replace($insertPart,
    'FROM\s+`(sandbox-lakehouse\.mart_finance\.v6_silver_[^`]+)`',
    'FROM (SELECT * FROM `$1` WHERE run_id = current_run_id)')
  # Wrap stg references in fct (FROM only)
  $insertPart = [regex]::Replace($insertPart,
    'FROM\s+`(sandbox-lakehouse\.stg_finance\.v6_stg_[^`]+)`',
    'FROM (SELECT * FROM `$1` WHERE run_id = current_run_id)')
  $insertIndented = ($insertPart -split "`n" | ForEach-Object { if ($_ -match '\S') { "      $_" } else { "" } }) -join "`n"
  [void]$sb.AppendLine("      -- fct: $t (from $f)")
  [void]$sb.AppendLine($insertIndented)
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'FCT_$($t.ToUpper())_DONE', current_run_id, NULL);")
  [void]$sb.AppendLine("")
}

# ============================================================
# AUDIT — write one row per (run_id, table) to polaris_raw.run_audit
# ============================================================
[void]$sb.AppendLine("      -- ---- AUDIT (33 rows, one per table) ----")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'AUDIT_START', current_run_id, NULL);")
[void]$sb.AppendLine("")

# Build the (table_name, layer, dataset) tuple list + per-table count UNION
$auditTuples = @()
$auditCounts = @()
foreach ($t in $stgTables) {
  $auditTuples += "STRUCT('$t' AS table_name, 'stg' AS layer)"
  $auditCounts += "SELECT '$t' AS table_name, COUNT(*) AS row_count FROM ``sandbox-lakehouse.stg_finance.$t`` WHERE run_id = current_run_id"
}
foreach ($t in $silverTables) {
  $auditTuples += "STRUCT('$t', 'silver')"
  $auditCounts += "SELECT '$t', COUNT(*) FROM ``sandbox-lakehouse.mart_finance.$t`` WHERE run_id = current_run_id"
}
foreach ($t in $fctTables) {
  $auditTuples += "STRUCT('$t', 'fct')"
  $auditCounts += "SELECT '$t', COUNT(*) FROM ``sandbox-lakehouse.fct_finance.$t`` WHERE run_id = current_run_id"
}
$auditTuplesSql = $auditTuples -join ",`n          "
$auditCountsSql = $auditCounts -join "`n        UNION ALL "

$auditInsert = @"
      INSERT INTO ``sandbox-lakehouse.polaris_raw.run_audit``
      (run_id, run_label, run_type, table_name, layer, row_count, has_data, processed_at)
      WITH
      label_src AS (
        SELECT MAX(run_label) AS run_label, MAX(run_type) AS run_type
        FROM ``sandbox-lakehouse.polaris_raw.v6_raw_inputs_tab``
        WHERE run_id = current_run_id
      ),
      tbls AS (
        SELECT * FROM UNNEST([
          $auditTuplesSql
        ])
      ),
      counts AS (
        $auditCountsSql
      )
      SELECT
        current_run_id      AS run_id,
        (SELECT run_label FROM label_src) AS run_label,
        (SELECT run_type  FROM label_src) AS run_type,
        t.table_name,
        t.layer,
        COALESCE(c.row_count, 0)         AS row_count,
        COALESCE(c.row_count, 0) > 0     AS has_data,
        CURRENT_TIMESTAMP()              AS processed_at
      FROM tbls t
      LEFT JOIN counts c USING (table_name);
"@

[void]$sb.AppendLine($auditInsert)
[void]$sb.AppendLine("")
[void]$sb.AppendLine("      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'AUDIT_DONE', current_run_id, NULL);")
[void]$sb.AppendLine("")

# ============================================================
# Footer
# ============================================================
[void]$sb.AppendLine(@'
      SET processed_count = processed_count + 1;
      INSERT INTO _log VALUES (CURRENT_TIMESTAMP(), 'RUN_DONE', current_run_id, NULL);
    END IF;
  END FOR;

  INSERT INTO _log VALUES (
    CURRENT_TIMESTAMP(), 'PIPELINE_DONE', NULL,
    FORMAT('Processed=%d, Skipped=%d', processed_count, skipped_count)
  );

  SELECT * FROM _log ORDER BY ts;
END;
'@)

$txt = $sb.ToString()
[System.IO.File]::WriteAllText($out, $txt, [System.Text.UTF8Encoding]::new($false))

"Wrote: $out"
"Size: $((Get-Item $out).Length) bytes"
"Lines: $((Get-Content $out | Measure-Object -Line).Lines)"
